name: CI/CD to Docker Hub and Deploy

on:
  push:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t basic-crud:latest .

      - name: Tag Docker image
        run: docker tag basic-crud:latest widhofaisal/basic-crud:latest

      - name: Push Docker image
        run: docker push widhofaisal/basic-crud:latest

      - name: Create .env file
        run: |
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "PORT=3306" >> .env
          echo "HOST=mysql" >> .env
          echo "DB_DB=${{ secrets.DB_DB }}" >> .env

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            echo ${{ secrets.SSH_ROOT_PASSWORD }} | sudo -S docker pull widhofaisal/basic-crud:latest
            echo ${{ secrets.SSH_ROOT_PASSWORD }} | sudo -S docker stop container_basic_crud
            echo ${{ secrets.SSH_ROOT_PASSWORD }} | sudo -S docker rm -v container_basic_crud
            echo ${{ secrets.SSH_ROOT_PASSWORD }} | sudo -S docker run -d -it -p 9000:9000 --name container_basic_crud  --link container_mysql:mysql -e DB_HOST=mysql -e DB_PORT=3306 -e DB_USER=developerbackend -e DB_PASSWORD=9JpJTk4nRMc2EPNOjGgZWNKOHDdaeT -e DB_NAME=simakpro_db widhofaisal/basic-crud:latest